config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "steps#index"

  resources :steps

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/step.rb
class Step < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
    @steps = Step.all
  end

  def show
    @step = Step.find(params[:id])
  end

  def new # show form
    @step = Step.new
  end

  def create # take data submitted by form, make thing, includes validation
    @step = Step.new(step_params)

    if @step.save
      redirect_to @step
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit # show form
    @step = Step.find(params[:id])
  end

  def update # take data submitted by form, update thing, includes validation
    @step = Step.find(params[:id])

    if @step.update(step_params)
      redirect_to @step
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def step_params
      params.require(:step).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/steps/_form.html.erb
<%= form_with model: step do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% step.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% step.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Edit Step</h1>

<%= render "form", step: @step %>

app/views/steps/index.html.erb
<h1>Steps needed to set up docker for Rails </h1>
<ol>
  <% @steps.each do |step| %>
    <li>
      <%= link_to(step.name, step) %>
    </li>
  <% end %>
</ol>

<%= link_to("Create New Step", new_step_path) %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render "form", step: @step %>

app/views/steps/show.html.erb
<h1><%= @step.name %></h1>

<p><%= @step.description %></p>

<ul>
  <li><%= link_to("Edit Step", edit_step_path(@step)) %></li>
  <li><%= link_to "Destroy Step", @step, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to("Back to overview", root_path) %></li>
</ul>